-- Recommendations table: editable product mapping for each (skin_tone, lip_tone, category)
CREATE TABLE public.recommendations (
  skin_tone text NOT NULL,
  lip_tone text NOT NULL,
  category text NOT NULL,
  variant_name text NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now(),
  updated_by uuid,
  PRIMARY KEY (skin_tone, lip_tone, category)
);

GRANT SELECT ON public.recommendations TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.recommendations TO authenticated;
GRANT ALL ON public.recommendations TO service_role;

ALTER TABLE public.recommendations ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Public can read recommendations"
  ON public.recommendations FOR SELECT
  USING (true);

CREATE POLICY "Authenticated can insert recommendations"
  ON public.recommendations FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY "Authenticated can update recommendations"
  ON public.recommendations FOR UPDATE TO authenticated
  USING (true) WITH CHECK (true);

CREATE POLICY "Authenticated can delete recommendations"
  ON public.recommendations FOR DELETE TO authenticated
  USING (true);

INSERT INTO public.recommendations (skin_tone, lip_tone, category, variant_name) VALUES
('light-brown','bright-pink','MLBB','Farrah'),
('light-brown','bright-pink','RED','Jiya'),
('light-brown','bright-pink','DAY','Ruchi'),
('light-brown','bright-pink','EVENING','Saanvi'),
('light-brown','bright-pink','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','brown-pink','MLBB','Amira'),
('light-brown','brown-pink','RED','Jiya'),
('light-brown','brown-pink','DAY','Farrah'),
('light-brown','brown-pink','EVENING','Saanvi'),
('light-brown','brown-pink','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','mauve-pink','MLBB','Amira'),
('light-brown','mauve-pink','RED','Kiran'),
('light-brown','mauve-pink','DAY','Farrah'),
('light-brown','mauve-pink','EVENING','Saanvi'),
('light-brown','mauve-pink','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','beige','MLBB','Amira'),
('light-brown','beige','RED','Kiran'),
('light-brown','beige','DAY','Farrah'),
('light-brown','beige','EVENING','Saanvi'),
('light-brown','beige','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','two-toned-purple','MLBB','Amira'),
('light-brown','two-toned-purple','RED','Kiran'),
('light-brown','two-toned-purple','DAY','Anjali'),
('light-brown','two-toned-purple','EVENING','Saanvi'),
('light-brown','two-toned-purple','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','two-toned-brown','MLBB','Amira'),
('light-brown','two-toned-brown','RED','Kiran'),
('light-brown','two-toned-brown','DAY','Anjali'),
('light-brown','two-toned-brown','EVENING','Saanvi'),
('light-brown','two-toned-brown','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','two-toned-grey','MLBB','Amira'),
('light-brown','two-toned-grey','RED','Kiran'),
('light-brown','two-toned-grey','DAY','Anjali'),
('light-brown','two-toned-grey','EVENING','Saanvi'),
('light-brown','two-toned-grey','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','two-toned-beige','MLBB','Amira'),
('light-brown','two-toned-beige','RED','Kiran'),
('light-brown','two-toned-beige','DAY','Anjali'),
('light-brown','two-toned-beige','EVENING','Saanvi'),
('light-brown','two-toned-beige','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','neutral-brown','MLBB','Saanvi'),
('light-brown','neutral-brown','RED','Kiran'),
('light-brown','neutral-brown','DAY','Anjali'),
('light-brown','neutral-brown','EVENING','Saanvi'),
('light-brown','neutral-brown','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','medium-brown','MLBB','Saanvi'),
('light-brown','medium-brown','RED','Kiran'),
('light-brown','medium-brown','DAY','Anjali'),
('light-brown','medium-brown','EVENING','Saanvi'),
('light-brown','medium-brown','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','deep-brown','MLBB','Saanvi'),
('light-brown','deep-brown','RED','Kiran'),
('light-brown','deep-brown','DAY','Anjali'),
('light-brown','deep-brown','EVENING','Saanvi'),
('light-brown','deep-brown','LIPSET','Lip Set for Light Brown Skin'),
('light-brown','grey-brown','MLBB','Saanvi'),
('light-brown','grey-brown','RED','Kiran'),
('light-brown','grey-brown','DAY','Anjali'),
('light-brown','grey-brown','EVENING','Saanvi'),
('light-brown','grey-brown','LIPSET','Lip Set for Light Brown Skin'),
('medium-brown','bright-pink','MLBB','Amira'),
('medium-brown','bright-pink','RED','Jiya'),
('medium-brown','bright-pink','DAY','Neha'),
('medium-brown','bright-pink','EVENING','Saanvi'),
('medium-brown','bright-pink','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','brown-pink','MLBB','Amira'),
('medium-brown','brown-pink','RED','Jiya'),
('medium-brown','brown-pink','DAY','Neha'),
('medium-brown','brown-pink','EVENING','Saanvi'),
('medium-brown','brown-pink','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','mauve-pink','MLBB','Amira'),
('medium-brown','mauve-pink','RED','Kiran'),
('medium-brown','mauve-pink','DAY','Neha'),
('medium-brown','mauve-pink','EVENING','Saanvi'),
('medium-brown','mauve-pink','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','beige','MLBB','Amira'),
('medium-brown','beige','RED','Kiran'),
('medium-brown','beige','DAY','Neha'),
('medium-brown','beige','EVENING','Saanvi'),
('medium-brown','beige','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','two-toned-purple','MLBB','Saanvi'),
('medium-brown','two-toned-purple','RED','Kiran'),
('medium-brown','two-toned-purple','DAY','Neha'),
('medium-brown','two-toned-purple','EVENING','Saanvi'),
('medium-brown','two-toned-purple','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','two-toned-brown','MLBB','Saanvi'),
('medium-brown','two-toned-brown','RED','Kiran'),
('medium-brown','two-toned-brown','DAY','Neha'),
('medium-brown','two-toned-brown','EVENING','Saanvi'),
('medium-brown','two-toned-brown','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','two-toned-grey','MLBB','Saanvi'),
('medium-brown','two-toned-grey','RED','Kiran'),
('medium-brown','two-toned-grey','DAY','Neha'),
('medium-brown','two-toned-grey','EVENING','Saanvi'),
('medium-brown','two-toned-grey','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','two-toned-beige','MLBB','Saanvi'),
('medium-brown','two-toned-beige','RED','Kiran'),
('medium-brown','two-toned-beige','DAY','Neha'),
('medium-brown','two-toned-beige','EVENING','Saanvi'),
('medium-brown','two-toned-beige','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','neutral-brown','MLBB','Riya'),
('medium-brown','neutral-brown','RED','Kiran'),
('medium-brown','neutral-brown','DAY','Neha'),
('medium-brown','neutral-brown','EVENING','Saanvi'),
('medium-brown','neutral-brown','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','medium-brown','MLBB','Riya'),
('medium-brown','medium-brown','RED','Kiran'),
('medium-brown','medium-brown','DAY','Neha'),
('medium-brown','medium-brown','EVENING','Saanvi'),
('medium-brown','medium-brown','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','deep-brown','MLBB','Riya'),
('medium-brown','deep-brown','RED','Kiran'),
('medium-brown','deep-brown','DAY','Neha'),
('medium-brown','deep-brown','EVENING','Saanvi'),
('medium-brown','deep-brown','LIPSET','Lip Set for Medium Brown Skin'),
('medium-brown','grey-brown','MLBB','Riya'),
('medium-brown','grey-brown','RED','Kiran'),
('medium-brown','grey-brown','DAY','Neha'),
('medium-brown','grey-brown','EVENING','Saanvi'),
('medium-brown','grey-brown','LIPSET','Lip Set for Medium Brown Skin'),
('deep-brown','bright-pink','MLBB','Neha'),
('deep-brown','bright-pink','RED','Jiya'),
('deep-brown','bright-pink','DAY','Neha'),
('deep-brown','bright-pink','EVENING','Saanvi'),
('deep-brown','bright-pink','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','brown-pink','MLBB','Neha'),
('deep-brown','brown-pink','RED','Jiya'),
('deep-brown','brown-pink','DAY','Neha'),
('deep-brown','brown-pink','EVENING','Saanvi'),
('deep-brown','brown-pink','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','mauve-pink','MLBB','Neha'),
('deep-brown','mauve-pink','RED','Kiran'),
('deep-brown','mauve-pink','DAY','Neha'),
('deep-brown','mauve-pink','EVENING','Saanvi'),
('deep-brown','mauve-pink','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','beige','MLBB','Neha'),
('deep-brown','beige','RED','Jiya'),
('deep-brown','beige','DAY','Neha'),
('deep-brown','beige','EVENING','Saanvi'),
('deep-brown','beige','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','two-toned-purple','MLBB','Saanvi'),
('deep-brown','two-toned-purple','RED','Kiran'),
('deep-brown','two-toned-purple','DAY','Riya'),
('deep-brown','two-toned-purple','EVENING','Riya'),
('deep-brown','two-toned-purple','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','two-toned-brown','MLBB','Saanvi'),
('deep-brown','two-toned-brown','RED','Kiran'),
('deep-brown','two-toned-brown','DAY','Riya'),
('deep-brown','two-toned-brown','EVENING','Riya'),
('deep-brown','two-toned-brown','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','two-toned-grey','MLBB','Saanvi'),
('deep-brown','two-toned-grey','RED','Kiran'),
('deep-brown','two-toned-grey','DAY','Riya'),
('deep-brown','two-toned-grey','EVENING','Riya'),
('deep-brown','two-toned-grey','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','two-toned-beige','MLBB','Saanvi'),
('deep-brown','two-toned-beige','RED','Kiran'),
('deep-brown','two-toned-beige','DAY','Neha'),
('deep-brown','two-toned-beige','EVENING','Riya'),
('deep-brown','two-toned-beige','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','neutral-brown','MLBB','Pooja'),
('deep-brown','neutral-brown','RED','Kiran'),
('deep-brown','neutral-brown','DAY','Neha'),
('deep-brown','neutral-brown','EVENING','Riya'),
('deep-brown','neutral-brown','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','medium-brown','MLBB','Pooja'),
('deep-brown','medium-brown','RED','Kiran'),
('deep-brown','medium-brown','DAY','Neha'),
('deep-brown','medium-brown','EVENING','Riya'),
('deep-brown','medium-brown','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','deep-brown','MLBB','Pooja'),
('deep-brown','deep-brown','RED','Kiran'),
('deep-brown','deep-brown','DAY','Neha'),
('deep-brown','deep-brown','EVENING','Riya'),
('deep-brown','deep-brown','LIPSET','Lip Set for Deep Brown Skin'),
('deep-brown','grey-brown','MLBB','Pooja'),
('deep-brown','grey-brown','RED','Kiran'),
('deep-brown','grey-brown','DAY','Neha'),
('deep-brown','grey-brown','EVENING','Riya'),
('deep-brown','grey-brown','LIPSET','Lip Set for Deep Brown Skin'),
('rich-brown','bright-pink','MLBB','Neha'),
('rich-brown','bright-pink','RED','Jiya'),
('rich-brown','bright-pink','DAY','Neha'),
('rich-brown','bright-pink','EVENING','Aaliyah'),
('rich-brown','bright-pink','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','brown-pink','MLBB','Neha'),
('rich-brown','brown-pink','RED','Jiya'),
('rich-brown','brown-pink','DAY','Neha'),
('rich-brown','brown-pink','EVENING','Aaliyah'),
('rich-brown','brown-pink','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','mauve-pink','MLBB','Neha'),
('rich-brown','mauve-pink','RED','Kiran'),
('rich-brown','mauve-pink','DAY','Neha'),
('rich-brown','mauve-pink','EVENING','Aaliyah'),
('rich-brown','mauve-pink','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','beige','MLBB','Neha'),
('rich-brown','beige','RED','Kiran'),
('rich-brown','beige','DAY','Neha'),
('rich-brown','beige','EVENING','Aaliyah'),
('rich-brown','beige','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','two-toned-purple','MLBB','Pooja'),
('rich-brown','two-toned-purple','RED','Kiran'),
('rich-brown','two-toned-purple','DAY','Neha'),
('rich-brown','two-toned-purple','EVENING','Aaliyah'),
('rich-brown','two-toned-purple','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','two-toned-brown','MLBB','Pooja'),
('rich-brown','two-toned-brown','RED','Kiran'),
('rich-brown','two-toned-brown','DAY','Neha'),
('rich-brown','two-toned-brown','EVENING','Aaliyah'),
('rich-brown','two-toned-brown','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','two-toned-grey','MLBB','Pooja'),
('rich-brown','two-toned-grey','RED','Kiran'),
('rich-brown','two-toned-grey','DAY','Neha'),
('rich-brown','two-toned-grey','EVENING','Aaliyah'),
('rich-brown','two-toned-grey','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','two-toned-beige','MLBB','Pooja'),
('rich-brown','two-toned-beige','RED','Kiran'),
('rich-brown','two-toned-beige','DAY','Neha'),
('rich-brown','two-toned-beige','EVENING','Aaliyah'),
('rich-brown','two-toned-beige','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','neutral-brown','MLBB','Amrit'),
('rich-brown','neutral-brown','RED','Kiran'),
('rich-brown','neutral-brown','DAY','Aaliyah'),
('rich-brown','neutral-brown','EVENING','Aaliyah'),
('rich-brown','neutral-brown','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','medium-brown','MLBB','Amrit'),
('rich-brown','medium-brown','RED','Kiran'),
('rich-brown','medium-brown','DAY','Aaliyah'),
('rich-brown','medium-brown','EVENING','Aaliyah'),
('rich-brown','medium-brown','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','deep-brown','MLBB','Amrit'),
('rich-brown','deep-brown','RED','Kiran'),
('rich-brown','deep-brown','DAY','Aaliyah'),
('rich-brown','deep-brown','EVENING','Aaliyah'),
('rich-brown','deep-brown','LIPSET','Lip Set for Rich Brown Skin'),
('rich-brown','grey-brown','MLBB','Amrit'),
('rich-brown','grey-brown','RED','Kiran'),
('rich-brown','grey-brown','DAY','Aaliyah'),
('rich-brown','grey-brown','EVENING','Amrit'),
('rich-brown','grey-brown','LIPSET','Lip Set for Rich Brown Skin');